stages:
  - build

build:
  stage: build
  script:
    - docker login harbor.zinza.com.vn
    - docker build -t harbor.zinza.com.vn/hieulv/training-server .
    - docker push harbor.zinza.com.vn/hieulv/training-server
