image: node:14

services:
  - localstack/localstack

stages:
  - build
  - test
  - release
  - deploy

build:
  stage: build
  script:
    - npm start

test:
  stage: test
  script:
    - npm start

release-image:
  stage: release
  script:
    - npm start
  

deploy:
  stage: deploy
  script:
    - npm start

