image: node:14

services:
  - localstack/localstack

cache:
  paths:
    - node_modules/

stages:
  - test
  - build

test server:
  stage: test
  script:
    - npm install
    - npm start

build server:
  stage: build
  script:
    - npm install
    - npm start


