stages:
  - build
before_script:
  - docker info

build server:
  stage: build
  image: docker:latest
  services:
    - docker:18.09.7-dind
    - localstacl/localstack:lastest
  script:
    - docker build -t training-server_server:latest

