version: "3"

services:
  server:
    container_name: serverapp
    build:
      context: .
    ports:
      - "5000:80"
    volumes:
      - .:/src
      - /src/node_modules
    networks:
      - server-app
    depends_on:
      - mongo
      - localstack

  mongo:
    image: mongo
    volumes:
      - "./data:/data/db"
    networks:
      - server-app

  localstack:
    image: localstack/localstack
    volumes:
      - "./localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    networks:
      - server-app

networks:
  server-app:
    driver: bridge
