version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # networks:
    #   - server-app
    # depends_on:
    #   - localstack
    #   - mongo

  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   restart: unless-stopped
  #   volumes:
  #     - ./data:/data/db
  #   networks:
  #     - server-app

  # localstack:
  #   image: localstack/localstack
  #   ports:
  #     - "4566-4599:4566-4599"
  #   volumes:
  #     - "./localstack:/tmp/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   environment:
  #     - SERVICES=s3
  #     - DEBUG=1
  #     - DATA_DIR=/tmp/localstack/data
  #   networks:
  #     - server-app

  client:
    build:
      context: ../training-client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
# networks:
#   server-app:
#     driver: bridge
