version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  client:
    build:
      context: ../training-client
      dockerfile: Dockerfile
