version: "3"

services:
  server:
    build:
      context: .
    container_name: server-production
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - server-app
    depends_on:
      - localstack
      # - mongo

  #   mongo:
  #     image: mongo
  #     ports:
  #       - "27017:27017"
  #     restart: unless-stopped
  #     volumes:
  #       - ./data:/data/db
  #     networks:
  #       - server-app

  localstack:
    image: localstack/localstack
    container_name: localstack-production
    ports:
      - "4566-4599:4566-4599"
    restart: unless-stopped
    volumes:
      - "./localstack/s3:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    networks:
      - server-app

networks:
  server-app:
    driver: bridge
