version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    networks:
      - server-app
    depends_on:
      - localstack
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27107:27107"
    networks:
      - server-app

  localstack:
    image: localstack/localstack
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
      - ./localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - server-app

  client:
    build:
      context: ../training-client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - server-app

networks:
  server-app:
    driver: bridge
