version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

  client:
    build:
      context: ../training-client
      dockerfile: Dockerfile
    ports:
      - "3050:80"
